# Setting
gpus: [0]
seed: 1
debug: False
pretrained_path:
work_dir: YOUR_PATH
no_progress_bar: False

# Visualization
visualization_class: 11
visualization_sample: 0
visualization_frames: []

# Data Loader
# ntu-xsub, ntu-xview, ntu-xsub120, ntu-xset120
dataset: ntu-xview
dataset_args:
  ntu:
    train_batch_size: 16
    eval_batch_size: 16
    num_frame: 288
    inputs: B
    transform: True
    root_folder: YOUR_PATH/data/npy_dataset
    ntu60_path: YOUR_PATH/nturgbd_skeletons_s001_to_s017
    ntu120_path: YOUR_PATH/nturgbd_skeletons_s018_to_s032

# Model
model_type: EfficientGCN-B0
model_args:
  stem_channel: 24
  block_args: [[48,1,0.5],[64,1,0.5],[128,2,1],[256,2,1]]
  fusion_stage: 4
  act_type: swish
  att_type: stja
  layer_type: SG
  drop_prob: 0.25
  kernel_size: [5,2]
  scale_args: [1.2,1.35]
  expand_ratio: 0
  reduct_ratio: 2
  bias: True
  edge: True

# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0001

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  cosine:
    max_epoch: 50
    warm_up: 10